version: '3'
services:

  discordbot:
    image: discordbot-template:latest
    build:
      context: ./bot
      dockerfile: Dockerfile
    env_file:
      - ./bot/.env
    restart: always

  fastapi:
    image: discordbot-api-template:latest
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    
    # Use expose if you don't want to access the api outside the docker network.
    # expose:
    #   - 8080

    ports:
      - "5500:8080"
    
