import discord
import os
import datetime
from utils import *

import logging
logging.basicConfig(format='[%(levelname)s][%(name)s] %(asctime)s | %(message)s', datefmt='%d-%b-%y %H:%M:%S', level=logging.INFO)

PREFIX = os.getenv('PREFIX', '!')
DISCORD_TOKEN = os.getenv('DISCORD_TOKEN')

client = discord.Client()

# Load text commands
commands_dict = load_commands()
commands_embed = generate_command_embed(commands_dict, PREFIX)

@client.event
async def on_ready():
    logging.info('We have logged in as {0.user}'.format(client))

@client.event
async def on_message(message):
    # This is for basic text replies fetched from commands.json
    for command in commands_dict:
        if message.content.startswith(f'{PREFIX}{command["command"]}'):
            if "response" in list(command.keys()):
                await message.channel.send(command['response'])
            break
    
    # This is for commands that require a response generation
    if message.content.startswith(f'{PREFIX}generated'):
        logging.info("Sending generated response 1")
        await message.channel.send(f'This response is dynamically generated at {datetime.datetime.now()}')

    if message.content.startswith(f'{PREFIX}response2'):
        logging.info("Sending generated response 2")
        await message.channel.send("This response is generated by the bot itself")

    elif message.content.startswith(f'{PREFIX}commands'):
        logging.info('Sending commands list')
        await message.channel.send(embed=commands_embed)

client.run(DISCORD_TOKEN)