# This is a basic workflow to help you get started with Actions

name: 'Bot: Image build'

# Controls when the workflow will run
on:    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
        tag:
          description: 'Version or tag'     
          required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_image:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      CR_PAT: ${{ secrets.PAT }}
      CR_USER: ${GITHUB_REPOSITORY_OWNER}
      PACKAGE: discordbot
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Github Registry Login
        run: echo $CR_PAT | docker login ghcr.io -u $CR_USER --password-stdin

      - name: downcase REPO
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Construct image name
        run: echo "IMAGE=ghcr.io/${REPO}/${PACKAGE}" >>${GITHUB_ENV}

      - name: Append label to Dockerfile
        run: echo LABEL org.opencontainers.image.source https://github.com/${REPO} >> bot/Dockerfile

      - name: Build Image
        run: |
          cd bot
          docker build -t ${IMAGE}:latest -t ${IMAGE}:${{ github.event.inputs.tag }} .
      
      - name: Push Image Versioned
        run: docker push ${IMAGE}:${{ github.event.inputs.tag }}

      - name: Push Image Latest
        run: docker push ${IMAGE}:latest
    